

server:
  port: 8083
  servlet:
    context-path: /

spring:
  jackson:
    default-property-inclusion: non_null
  application:
    name: college-service-order
  datasource:
    url: jdbc:mysql://10.228.81.19:38309/eop_finance_dev?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password:
    driverClassName: com.mysql.cj.jdbc.Driver
    testWhileIdle: true
    validationQuery: select 1
    testOnBorrow: false
    validationInterval: 1000
    minIdle: 10
    maxIdle: 15
    maxActive: 8
    initialSize: 8
    testOnConnect: true
    initSQL: select 1
#    mybatis 驼峰处理
mybatis:
  configuration:
    map-underscore-to-camel-case: true
rocketmq:
  name-server: 192.168.138.3:9876
  producer:
    group: springcloud-producter
    send-message-timeout: 5000
  topic: springboot_producer
  consumer:
    group: college_consumer
